## Some experiments

In [3]:
import torch
from torch import nn

In [5]:
x = torch.tensor([1., 2., 3.])
print(x.dtype, x.shape)

torch.float32 torch.Size([3])


In [7]:
x = x.unsqueeze(0)

In [9]:
rnn = nn.RNN(input_size = 3, hidden_size=2, num_layers = 2)

In [11]:
out, hidden = rnn(x)

In [13]:
out

tensor([[ 0.7024, -0.0048]], grad_fn=<SqueezeBackward1>)

In [15]:
hidden

tensor([[ 0.5007,  0.1150],
        [ 0.7024, -0.0048]], grad_fn=<SqueezeBackward1>)

In [43]:
import torch.nn as nn
torch.manual_seed(1)
inputs = [torch.randn(1, 3) for _ in range(5)] 
hidden = (torch.randn(1, 1, 3),
          torch.randn(1, 1, 3))
inputs, hidden

([tensor([[0.6614, 0.2669, 0.0617]]),
  tensor([[ 0.6213, -0.4519, -0.1661]]),
  tensor([[-1.5228,  0.3817, -1.0276]]),
  tensor([[-0.5631, -0.8923, -0.0583]]),
  tensor([[-0.1955, -0.9656,  0.4224]])],
 (tensor([[[ 0.2673, -0.4212, -0.5107]]]),
  tensor([[[-1.5727, -0.1232,  3.5870]]])))

In [45]:
lstm = nn.LSTM(input_size=3, hidden_size=3, num_layers=1, batch_first = True)
for i in inputs:
    # Step through the sequence one element at a time.
    # after each step, hidden contains the hidden state.
    out, hidden = lstm(i.view(1, 1, -1), hidden)
    print('out:', out)
    print('hidden:', hidden)

out: tensor([[[-0.1124, -0.0653,  0.2808]]], grad_fn=<TransposeBackward0>)
hidden: (tensor([[[-0.1124, -0.0653,  0.2808]]], grad_fn=<StackBackward0>), tensor([[[-0.2883, -0.2846,  2.0720]]], grad_fn=<StackBackward0>))
out: tensor([[[ 0.1675, -0.0376,  0.4402]]], grad_fn=<TransposeBackward0>)
hidden: (tensor([[[ 0.1675, -0.0376,  0.4402]]], grad_fn=<StackBackward0>), tensor([[[ 0.4394, -0.1226,  1.5611]]], grad_fn=<StackBackward0>))
out: tensor([[[0.3699, 0.0150, 0.1429]]], grad_fn=<TransposeBackward0>)
hidden: (tensor([[[0.3699, 0.0150, 0.1429]]], grad_fn=<StackBackward0>), tensor([[[0.8432, 0.0618, 0.9413]]], grad_fn=<StackBackward0>))
out: tensor([[[0.1795, 0.0296, 0.2957]]], grad_fn=<TransposeBackward0>)
hidden: (tensor([[[0.1795, 0.0296, 0.2957]]], grad_fn=<StackBackward0>), tensor([[[0.4541, 0.1121, 0.9320]]], grad_fn=<StackBackward0>))
out: tensor([[[0.1365, 0.0596, 0.3931]]], grad_fn=<TransposeBackward0>)
hidden: (tensor([[[0.1365, 0.0596, 0.3931]]], grad_fn=<StackBackward0>), t

In [47]:
import torch.nn as nn
torch.manual_seed(1)
inputs = [torch.randn(1, 3) for _ in range(5)] # indicates that there are 5 sequences to be given as inputs and (1,3) indicates that there is 1 layer with 3 cells
hidden = (torch.randn(1, 1, 3),
          torch.randn(1, 1, 3)) #initializing h and c values to be of dimensions (1, 1, 3) which indicates there is (1 * 1) - num_layers * num_directions, with batch size of 1 and projection size of 3. 
                                #Since there is only 1 batch in input, h and c can also have only one batch of data for initialization and the number of cells in both input and output should also match.
 
lstm = nn.LSTM(3, 3) #implying both input and output are 3 dimensional data
for i in inputs:
    out, hidden = lstm(i.view(1, 1, -1), hidden) #view to transform the shape of i from (1, 3) into (1, 1, 3) which of the form (Batch, M, N)
    print('out:', out)
    print('hidden:', hidden)

out: tensor([[[-0.1124, -0.0653,  0.2808]]], grad_fn=<MkldnnRnnLayerBackward0>)
hidden: (tensor([[[-0.1124, -0.0653,  0.2808]]], grad_fn=<StackBackward0>), tensor([[[-0.2883, -0.2846,  2.0720]]], grad_fn=<StackBackward0>))
out: tensor([[[ 0.1675, -0.0376,  0.4402]]], grad_fn=<MkldnnRnnLayerBackward0>)
hidden: (tensor([[[ 0.1675, -0.0376,  0.4402]]], grad_fn=<StackBackward0>), tensor([[[ 0.4394, -0.1226,  1.5611]]], grad_fn=<StackBackward0>))
out: tensor([[[0.3699, 0.0150, 0.1429]]], grad_fn=<MkldnnRnnLayerBackward0>)
hidden: (tensor([[[0.3699, 0.0150, 0.1429]]], grad_fn=<StackBackward0>), tensor([[[0.8432, 0.0618, 0.9413]]], grad_fn=<StackBackward0>))
out: tensor([[[0.1795, 0.0296, 0.2957]]], grad_fn=<MkldnnRnnLayerBackward0>)
hidden: (tensor([[[0.1795, 0.0296, 0.2957]]], grad_fn=<StackBackward0>), tensor([[[0.4541, 0.1121, 0.9320]]], grad_fn=<StackBackward0>))
out: tensor([[[0.1365, 0.0596, 0.3931]]], grad_fn=<MkldnnRnnLayerBackward0>)
hidden: (tensor([[[0.1365, 0.0596, 0.3931]]], gra

![image](img/SjnTl.png)



In [55]:
import torch
import torch.nn as nn

torch.manual_seed(0)
model = nn.LSTM( input_size = 1, hidden_size = 5, num_layers = 1)
x = torch.rand(10, 1, 1)
output, (hn, cn) = model(x)

In [57]:
output[-1]

tensor([[-0.1499, -0.2004, -0.2470,  0.0773,  0.0717]],
       grad_fn=<SelectBackward0>)

In [59]:
hn

tensor([[[-0.1499, -0.2004, -0.2470,  0.0773,  0.0717]]],
       grad_fn=<StackBackward0>)

In [61]:
import torch
import torch.nn as nn

torch.manual_seed(0)
model = nn.LSTM(input_size = 1, hidden_size = 50, num_layers = 1)
x = torch.rand(50, 1, 1)
output, (hn, cn) = model(x)

In [63]:
output.shape

torch.Size([50, 1, 50])

In [65]:
hn

tensor([[[ 0.1140, -0.0600, -0.0540,  0.1492, -0.0339, -0.0150, -0.0486,
           0.0188,  0.0504,  0.0595, -0.0176, -0.0035,  0.0384, -0.0274,
           0.1076,  0.0843, -0.0443,  0.0218, -0.0093,  0.0002,  0.1335,
           0.0926,  0.0101, -0.1300, -0.1141,  0.0072, -0.0142,  0.0018,
           0.0071,  0.0247,  0.0262,  0.0109,  0.0374,  0.0366,  0.0017,
           0.0466,  0.0063,  0.0295,  0.0536,  0.0339,  0.0528, -0.0305,
           0.0243, -0.0324,  0.0045, -0.1108, -0.0041, -0.1043, -0.0141,
          -0.1222]]], grad_fn=<StackBackward0>)

In [67]:
torch.zeros(1,2,3)

tensor([[[0., 0., 0.],
         [0., 0., 0.]]])

## RNN

In [71]:
import torch
import torch.nn.functional as F  # Parameterless functions, like (some) activation functions
import torchvision.datasets as datasets  # Standard datasets
import torchvision.transforms as transforms  # Transformations we can perform on our dataset for augmentation
from torch import optim  # For optimizers like SGD, Adam, etc.
from torch import nn  # All neural network modules
from torch.utils.data import (
    DataLoader,
)  # Gives easier dataset managment by creating mini batches etc.
from tqdm import tqdm  # For nice progress bar!
import matplotlib.pyplot as plt

In [83]:
# Hyperparameters
input_size = 28
hidden_size = 256
num_layers = 2
num_classes = 10
sequence_length = 28
learning_rate = 0.005
batch_size = 64
num_epochs = 3

# Set device
device = "cuda" if torch.cuda.is_available() else "cpu"

In [95]:
# Recurrent neural network (many-to-one)
class RNN(nn.Module):
    def __init__(self, input_size, hidden_size, num_layers, num_classes):
        super().__init__()
        self.hidden_size = hidden_size
        self.num_layers = num_layers
        self.rnn = nn.RNN(input_size, hidden_size, num_layers, batch_first=True)
        self.fc = nn.Linear(hidden_size * sequence_length, num_classes)

    def forward(self, x):
        # Set initial hidden and cell states
        h0 = torch.zeros(self.num_layers, x.size(0), self.hidden_size).to(device)

        # Forward propagate LSTM
        out, _ = self.rnn(x, h0)
        out = out.reshape(out.shape[0], -1)

        # Decode the hidden state of the last time step
        out = self.fc(out)
        return out

In [97]:
# Recurrent neural network with GRU (many-to-one)
class RNN_GRU(nn.Module):
    def __init__(self, input_size, hidden_size, num_layers, num_classes):
        super().__init__()
        self.hidden_size = hidden_size
        self.num_layers = num_layers
        self.gru = nn.GRU(input_size, hidden_size, num_layers, batch_first=True)
        self.fc = nn.Linear(hidden_size * sequence_length, num_classes)

    def forward(self, x):
        # Set initial hidden and cell states
        h0 = torch.zeros(self.num_layers, x.size(0), self.hidden_size).to(device)

        # Forward propagate LSTM
        out, _ = self.gru(x, h0)
        out = out.reshape(out.shape[0], -1)

        # Decode the hidden state of the last time step
        out = self.fc(out)
        return out

In [99]:
# Recurrent neural network with LSTM (many-to-one)
class RNN_LSTM(nn.Module):
    def __init__(self, input_size, hidden_size, num_layers, num_classes):
        super().__init__()
        self.hidden_size = hidden_size
        self.num_layers = num_layers
        self.lstm = nn.LSTM(input_size, hidden_size, num_layers, batch_first=True)
        self.fc = nn.Linear(hidden_size * sequence_length, num_classes)

    def forward(self, x):
        # Set initial hidden and cell states
        h0 = torch.zeros(self.num_layers, x.size(0), self.hidden_size).to(device)
        c0 = torch.zeros(self.num_layers, x.size(0), self.hidden_size).to(device)

        # Forward propagate LSTM
        out, _ = self.lstm(
            x, (h0, c0)
        )  # out: tensor of shape (batch_size, seq_length, hidden_size), (Batch, M, N) like the MxN matrix
        out = out.reshape(out.shape[0], -1)

        # Decode the hidden state of the last time step
        out = self.fc(out)
        return out

In [91]:
# Load Data
train_dataset = datasets.MNIST(
    root="dataset/", train=True, transform=transforms.ToTensor(), download=True
)
test_dataset = datasets.MNIST(
    root="dataset/", train=False, transform=transforms.ToTensor(), download=True
)
train_loader = DataLoader(dataset=train_dataset, batch_size=batch_size, shuffle=True)
test_loader = DataLoader(dataset=test_dataset, batch_size=batch_size, shuffle=True)

# Initialize network (try out just using simple RNN, or GRU, and then compare with LSTM)
model = RNN_LSTM(input_size, hidden_size, num_layers, num_classes).to(device)

# Loss and optimizer
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=learning_rate)

In [ ]:
# Train Network
model.train()
for epoch in range(num_epochs):
    for batch_idx, (data, targets) in enumerate(tqdm(train_loader)):
        # Get data to cuda if possible
        data = data.to(device=device).squeeze(1) #RNN expects the input size of the form (batch size, seq_length, input_size)
        targets = targets.to(device=device)      #We're having input size of the form (batch size, C, H, W)

        # forward
        scores = model(data)
        loss = criterion(scores, targets)

        # backward
        optimizer.zero_grad()
        loss.backward()

        # gradient descent update step/adam step
        optimizer.step()

In [93]:
# Check accuracy on training & test to see how good our model
def check_accuracy(loader, model):
    num_correct = 0
    num_samples = 0

    # Set model to eval
    model.eval()

    with torch.no_grad():
        for x, y in loader:
            x = x.to(device=device).squeeze(1)
            y = y.to(device=device)

            scores = model(x)
            _, predictions = scores.max(1)
            num_correct += (predictions == y).sum()
            num_samples += predictions.size(0)
    return num_correct / num_samples

In [ ]:
print(f"Accuracy on training set: {check_accuracy(train_loader, model)*100:2f}")
print(f"Accuracy on test set: {check_accuracy(test_loader, model)*100:.2f}")

## Squeeze method

In [155]:
test = torch.tensor([[[[1, 2, 3], [1, 2, 3]]], [[[1, 2, 3], [1, 2, 3]]]])
test.shape

torch.Size([2, 1, 2, 3])

In [157]:
test = test.squeeze(1)

In [159]:
test.shape

torch.Size([2, 2, 3])