In [52]:
import torch

# Scalar function

In [106]:
x = torch.rand(3, requires_grad = True)
x #Vector cần tính đạo gradient

tensor([0.6275, 0.2969, 0.6770], requires_grad=True)

In [108]:
y = torch.dot(x, x) #y = <x^T.X>
y.backward()
print(x.grad) #dy/dx

tensor([1.2551, 0.5938, 1.3541])


In [110]:
x.grad == 2 * x

tensor([True, True, True])

In [112]:
z = x.sum() #z = x1 + x2 + x3
z.backward()
print(x.grad) #ta thấy giá trị của dz/dx lẽ ra phải là [1, 1, 1] do z = x1 + x2 + x3, nhưng x.grad lại cộng cả giá trị của x.grad trước vào, đó là lí do
              #ta phải sử dụng x.grad.zero()
              #nếu ta chạy ô này nhiều lần sẽ thấy các grad cộng dồn vào nhau

tensor([2.2551, 1.5938, 2.3541])


In [114]:
z = x.sum()
x.grad.zero_()
z.backward()
print(x.grad)

tensor([1., 1., 1.])


# Vector function

In [197]:
x = torch.rand(3, requires_grad = True)
x #Vector cần tính đạo gradient

tensor([0.7157, 0.0155, 0.0827], requires_grad=True)

In [199]:
y = x * x
y

tensor([5.1228e-01, 2.3976e-04, 6.8433e-03], grad_fn=<MulBackward0>)

In [201]:
y.backward(torch.tensor([1.0, 1.0, 1.0]))
print(x.grad) #tính [dy1/dx1, ]

tensor([1.4315, 0.0310, 0.1654])


# Another example

In [226]:
a = torch.tensor([1., 2., 3.], requires_grad = True)
b = torch.tensor([1., 1., 2.], requires_grad = True)
Q = a * a + b * b
Q

tensor([ 2.,  5., 13.], grad_fn=<AddBackward0>)

In [230]:
Q.backward(torch.tensor([1, 1, 1]))
print(a.grad, b.grad)

#Q = [a1^2 + b1^2, a2^2 + b2^2, a3^2 + b3^2].T = [Q1, Q2, Q3].T
#a.grad là tính đạo hàm riêng theo a, nghĩa là tính [dQ1/da1, dQ2/da2, dQ3/da3], tương tự với b.grad

tensor([2., 4., 6.]) tensor([2., 2., 4.])
