In [49]:
import torch

# Scalar function

In [52]:
x = torch.rand(3, requires_grad = True)
x #Vector cần tính đạo gradient

tensor([0.3238, 0.0090, 0.1217], requires_grad=True)

In [54]:
y = torch.dot(x, x) #y = <x^T.X>
y.backward()
print(x.grad) #dy/dx tại x :  dy/dx(x) với x = torch.rand(3, requires_grad = True)

#Lưu ý x.grad chỉ có ý nghĩa sau khi đã gọi backward(), nếu chưa gọi backward() thì x.grad (dy/dx) == None

tensor([0.6477, 0.0180, 0.2435])


In [56]:
x.grad == 2 * x
# x.grad.zero_()

tensor([True, True, True])

In [58]:
z = x.sum() #z = x1 + x2 + x3
z.backward()
print(x.grad) #ta thấy giá trị của dz/dx lẽ ra phải là [1, 1, 1] do z = x1 + x2 + x3, nhưng x.grad lại cộng cả giá trị của x.grad trước vào, đó là lí do
              #ta phải sử dụng x.grad.zero() ở trên
              #nếu ta chạy ô này nhiều lần sẽ thấy các grad cộng dồn vào nhau

tensor([1.6477, 1.0180, 1.2435])


In [60]:
z = x.sum()
x.grad.zero_()
z.backward()
print(x.grad)

tensor([1., 1., 1.])


# Vector function

In [63]:
x = torch.rand(3, requires_grad = True)
x #Vector cần tính đạo gradient

tensor([0.7263, 0.4129, 0.7245], requires_grad=True)

In [65]:
y = x * x
y

tensor([0.5275, 0.1705, 0.5249], grad_fn=<MulBackward0>)

In [67]:
y.backward(torch.tensor([1.0, 1.0, 1.0]))
print(x.grad) #tính [dy1/dx1, ]

tensor([1.4525, 0.8258, 1.4489])


# Another example

In [70]:
a = torch.tensor([1., 2., 3.], requires_grad = True)
b = torch.tensor([1., 1., 2.], requires_grad = True)
Q = a * a + b * b
Q

tensor([ 2.,  5., 13.], grad_fn=<AddBackward0>)

In [72]:
Q.backward(torch.tensor([1, 1, 1]))
print(a.grad, b.grad)

#Q = [a1^2 + b1^2, a2^2 + b2^2, a3^2 + b3^2].T = [Q1, Q2, Q3].T
#a.grad là tính đạo hàm riêng theo a, nghĩa là tính [dQ1/da1, dQ2/da2, dQ3/da3], tương tự với b.grad

tensor([2., 4., 6.]) tensor([2., 2., 4.])
